const myProducts = [
  {
    id: "1",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Earrings",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1727990864588-757416bf8062?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTkxfHxqZXdlbHJ5fGVufDB8fDB8fHww",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'm',

  },
  {
    id: "2",
    name: "Catholic Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$25.00",
    oldPrice: "$ 49.99",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTZ8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5002-9093",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.5",
    gender: 'm',

  },
  {
    id: "3",
    name: "Rosegold Necklace set",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$105.00",
    oldPrice: "$ 179.99",
    image: "https://plus.unsplash.com/premium_photo-1681276170092-446cd1b5b32d?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8amV3ZWxyeXxlbnwwfHwwfHx8MA%3D%3D",
    ProductNumber: "1673-0003",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "3.5",
    gender: 'f',

  },
  {
    id: "4",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Brooch",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1693212793367-60001caf3b5e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjQwfHxqZXdlbHJ5fGVufDB8fDB8fHww",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'm',

  },
  {
    id: "5",
    name: "Pearl Earrings",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Earrings",
    price: "$35.00",
    oldPrice: "$ 40.02",
    image: "https://plus.unsplash.com/premium_photo-1681276170291-27698ccc0a8e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTIwfHxqZXdlbHJ5fGVufDB8fDB8fHww",
    ProductNumber: "1003-0093",
    varieties: "none yet",
    tags: "Bracelet, Jewellries",
    rating: "4.0",
    gender: 'm',

  },
  {
    id: "6",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Bracelets",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://plus.unsplash.com/premium_photo-1681276168324-a6f1958aa191?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODB8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'm',

  },
  {
    id: "7",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1719862056514-0cdacd9142b5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjAzfHxqZXdlbHJ5fGVufDB8fDB8fHww",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "8",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Rings",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1543295204-2ae345412549?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTJ8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "9",
    name: "Gold Hoop Earrings",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1569397288884-4d43d6738fbd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDJ8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "10",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Rings",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://plus.unsplash.com/premium_photo-1678554875441-b286d1b6174a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTN8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "11",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Earrings",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "12",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://plus.unsplash.com/premium_photo-1681276170281-cf50a487a1b7?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8amV3ZWxyeXxlbnwwfHwwfHx8MA%3D%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "13",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Earrings",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1600721391776-b5cd0e0048f9?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "14",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Rings",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1564623788399-b75405a129a2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzh8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "15",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Earrings",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1535556116002-6281ff3e9f36?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjh8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "16",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://plus.unsplash.com/premium_photo-1674255466849-b23fc5f5d3eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "17",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Earrings",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGpld2Vscnl8ZW58MHx8MHx8fDA%3D",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "18",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1721103428824-fc962ac61b63?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjk0fHxqZXdlbHJ5fGVufDB8fDB8fHww",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
  },
  {
    id: "19",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Earrings",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1674329042475-de1a95b4ca62?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjUyfHxqZXdlbHJ5fGVufDB8fDB8fHww",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'm',
  },
  {
    id: "20",
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: "https://images.unsplash.com/photo-1719861837593-91dbdd0ed5a0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjY2fHxqZXdlbHJ5fGVufDB8fDB8fHww",
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
    gender: 'f',
    brand: '',
  },
];

export default myProducts;