import instaImage2 from "../../assets/instapage-image-neckpiece.jpg";


export const products = [
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
  {
    name: "Vintage Double Neckpiece",
    description: "This is the most used props for routing. It helps in specifying the target location to which the link should navigate.It can be a string representing the path name or an object with path name. When you click on Dashboard you will be redirected to that component.This is the most used props for routing.It helps in specifying the target location to which the link should navigate. It can be a string representing the path name or an object with path name.When you click on Dashboard you will be redirected to that component.",
    category: "Necklaces",
    price: "$95.00",
    oldPrice: "$ 79.99",
    image: { instaImage2 },
    ProductNumber: "5672-9013",
    varieties: "none yet",
    tags: "Bracelet, Assesories",
    rating: "4.0",
  },
]